### ISSUE TITLE
Allow YamlRepository.new() to accept a hash?

### ISSUE THREAD

**Issue by cherbst-2112** [mgsnova/feature#14]
Hi, I just found your feature gem and it looks like exactly what I need!  I would like to have a different config for each environment though, like this:

```
development:
  features:
    feature_foo: true

test:
  features:
    feature_foo: true

production:
  features:
    feature_foo: false
```

This way I could have feature_foo on for development and my tests, but default it false in case we forget to disable it on deploy.  We could easily do this if YamlRepository.new() accepted a hash:

```
config_for_env = YAML.load_file("#{Rails.root}/config/feature.yml")[Rails.env]
repo = Feature::Repository::YamlRepository.new(config_for_env)
```

What do you think?  The code in `YamlRepository#read_and_parse_file_data()` should be able to refactor and support this easily, I'd be happy to send a pull request if this sounds like a good idea.
